name: Unit Tests

on:
  push:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(vars.DEFAULT_JOB_TIMEOUT_MINUTES) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Test
        run: |
          composer self-update && composer --version
          composer install --prefer-dist --no-interaction
          composer exec codecept build -v
          composer test -v
